import { Platform, StyleSheet } from "react-native";
import { SCREEN_LAYOUT } from "../theme/layout";

export const createAssistantStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingTop: SCREEN_LAYOUT.headerTopPadding,
      paddingHorizontal: SCREEN_LAYOUT.horizontalPadding,
      paddingBottom: 14,
      backgroundColor: colors.primarySoft,
      borderBottomLeftRadius: SCREEN_LAYOUT.heroRadius,
      borderBottomRightRadius: SCREEN_LAYOUT.heroRadius,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
      zIndex: 20,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    menuButton: {
      padding: 8,
      borderRadius: 12,
      backgroundColor: colors.card,
    },
    headerCenter: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
    },
    brandRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    brandIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 10,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    title: {
      fontSize: 19,
      fontWeight: "800",
      color: colors.text,
      letterSpacing: -0.5,
    },
    statusPill: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      backgroundColor: colors.card,
      borderRadius: 12,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    statusDotOnline: {
      backgroundColor: colors.primary,
    },
    statusDotChecking: {
      backgroundColor: colors.warning,
    },
    statusDotOffline: {
      backgroundColor: colors.danger,
    },
    statusText: {
      fontSize: 10,
      fontWeight: "700",
      color: colors.textSecondary,
      letterSpacing: 0.3,
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    iconButton: {
      padding: 8,
      borderRadius: 12,
      backgroundColor: colors.inputBg,
    },
    mainContainer: {
      flex: 1,
      position: "relative",
    },
    backdrop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.35)",
      zIndex: 50,
    },
    sidebar: {
      position: "absolute",
      top: 0,
      left: 0,
      bottom: 0,
      width: "82%",
      maxWidth: 340,
      backgroundColor: colors.surface,
      zIndex: 60,
      shadowColor: "#000",
      shadowOffset: { width: 4, height: 0 },
      shadowOpacity: 0.18,
      shadowRadius: 20,
      elevation: 20,
    },
    sidebarHeader: {
      paddingTop: Platform.OS === "ios" ? 56 : 24,
      paddingHorizontal: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sidebarBrand: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    sidebarTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: colors.text,
      letterSpacing: -0.5,
    },
    sidebarClose: {
      padding: 4,
    },
    sidebarAuthPill: {
      alignSelf: "flex-start",
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: colors.primarySoft,
      borderRadius: 12,
    },
    sidebarAuthText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.primaryDark,
    },
    sidebarUserRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    userNameText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
      flex: 1,
      marginRight: 12,
    },
    logoutPill: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
      backgroundColor: colors.dangerSoft,
    },
    logoutText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.danger,
    },
    sidebarList: {
      flex: 1,
      padding: 12,
    },
    emptyState: {
      alignItems: "center",
      marginTop: 40,
      paddingHorizontal: 20,
    },
    emptyStateIcon: {
      fontSize: 32,
      marginBottom: 8,
    },
    noSessionsText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
      textAlign: "center",
      marginBottom: 4,
    },
    emptyStateSub: {
      fontSize: 13,
      color: colors.textMuted,
      textAlign: "center",
    },
    sessionItemWrapper: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    sessionItem: {
      flex: 1,
      padding: 14,
    },
    sessionTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text,
      lineHeight: 18,
      marginBottom: 4,
    },
    sessionDate: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: "500",
    },
    deleteSessionButton: {
      padding: 14,
      justifyContent: "center",
      alignItems: "center",
    },
    chatArea: {
      flex: 1,
    },
    chatContainer: {
      flex: 1,
      padding: 16,
    },
    messageWrapper: {
      marginBottom: 20,
      flexDirection: "row",
      alignItems: "flex-end",
    },
    userWrapper: {
      justifyContent: "flex-end",
    },
    botWrapper: {
      justifyContent: "flex-start",
    },
    avatarCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primarySoft,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
      marginBottom: 4,
    },
    messageBubble: {
      maxWidth: "84%",
      padding: 14,
    },
    userBubble: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      borderBottomRightRadius: 4,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
      elevation: 4,
    },
    botBubble: {
      backgroundColor: colors.card,
      borderRadius: 20,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    messageMeta: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
    },
    senderLabel: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.primary,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    senderLabelUser: {
      color: colors.onPrimary,
      opacity: 0.9,
    },
    messageTime: {
      fontSize: 10,
      color: colors.textMuted,
      marginLeft: 8,
      fontWeight: "500",
    },
    metaBadgeWarning: {
      alignSelf: "flex-start",
      backgroundColor: colors.surfaceAlt,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      marginBottom: 8,
    },
    metaBadgeWarningText: {
      fontSize: 10,
      fontWeight: "700",
      color: colors.warning,
      letterSpacing: 0.3,
    },
    metaBadgeSource: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      backgroundColor: colors.primarySoft,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      marginBottom: 8,
      gap: 4,
    },
    metaBadgeSourceText: {
      fontSize: 10,
      fontWeight: "700",
      color: colors.primaryDark,
      letterSpacing: 0.3,
    },
    messageText: {
      fontSize: 15,
      lineHeight: 22,
      color: colors.text,
      fontWeight: "400",
    },
    messageTextUser: {
      color: colors.onPrimary,
    },
    messageTextSource: {
      color: colors.text,
    },
    actionRow: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 8,
    },
    actionRowLabel: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    actionPillRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    actionPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: colors.surfaceAlt,
    },
    actionPillActive: {
      backgroundColor: colors.primarySoft,
    },
    actionPillText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textSecondary,
    },
    actionPillTextActive: {
      color: colors.primaryDark,
    },
    showOriginalPill: {
      alignSelf: "flex-start",
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    showOriginalText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.primary,
    },
    sourcesPanel: {
      marginTop: 10,
      padding: 10,
      backgroundColor: colors.surface,
      borderRadius: 10,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
    },
    sourcesPanelTitle: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    sourcesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    sourceChip: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    sourceChipText: {
      fontSize: 10,
      fontWeight: "600",
      color: colors.textSecondary,
      maxWidth: 120,
    },
    sourceChipPage: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.primary,
    },
    sourceChipMore: {
      backgroundColor: colors.inputBg,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    sourceChipMoreText: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.textMuted,
    },
    loadingContainer: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      padding: 14,
      marginTop: 4,
      backgroundColor: colors.card,
      borderRadius: 20,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 10,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 2,
    },
    loadingText: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: "600",
    },
    errorContainer: {
      marginHorizontal: 16,
      marginBottom: 8,
      padding: 12,
      backgroundColor: colors.dangerSoft,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.danger,
      opacity: 0.95,
    },
    errorText: {
      fontSize: 12,
      color: colors.danger,
      fontWeight: "700",
      textAlign: "center",
      letterSpacing: 0.2,
    },
    inputSurface: {
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: Platform.OS === "ios" ? 20 : 12,
    },
    inputToolsToggle: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 8,
      marginTop: 4,
    },
    inputToolsToggleText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    inputToolsPanel: {
      marginTop: 4,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 12,
    },
    inputToolsHint: {
      fontSize: 11,
      lineHeight: 16,
      color: colors.textMuted,
      fontWeight: "500",
    },
    inputToolBlock: {
      gap: 6,
    },
    langLabel: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 2,
      marginLeft: 2,
    },
    langOptions: {
      flexDirection: "row",
      backgroundColor: colors.inputBg,
      borderRadius: 10,
      padding: 3,
      gap: 3,
    },
    langOption: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 5,
      borderRadius: 8,
    },
    langOptionActive: {
      backgroundColor: colors.card,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
      elevation: 1,
    },
    langOptionText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textMuted,
    },
    langOptionTextActive: {
      color: colors.text,
    },
    translateDraftButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      marginTop: 8,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: colors.primary,
    },
    translateDraftButtonDisabled: {
      opacity: 0.45,
    },
    translateDraftButtonText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.onPrimary,
    },
    inputRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 10,
    },
    input: {
      flex: 1,
      backgroundColor: colors.inputBg,
      borderRadius: 22,
      paddingHorizontal: 18,
      paddingVertical: 12,
      fontSize: 16,
      maxHeight: 120,
      color: colors.text,
      textAlignVertical: "top",
      lineHeight: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sendButton: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
      marginBottom: 2,
    },
    sendButtonDisabled: {
      opacity: 0.35,
    },
    trustBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      backgroundColor: colors.card,
      marginHorizontal: 12,
      marginBottom: 8,
      paddingVertical: 10,
      paddingHorizontal: 8,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 1,
    },
    trustItem: {
      alignItems: "center",
      flex: 1,
    },
    trustIconBg: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: colors.chipBg,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
    },
    trustText: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.textSecondary,
      textAlign: "center",
      letterSpacing: 0.3,
    },
    trustDivider: {
      width: 1,
      height: 20,
      backgroundColor: colors.border,
    },
  });