export const createCommunityStyles = (colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: colors.textSecondary,
  },
  header: {
    padding: 20,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.primaryDark,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  statsRow: {
    marginTop: 8,
  },
  statsText: {
    fontSize: 12,
    color: colors.textSecondary,
    backgroundColor: colors.chipBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  createButton: {
    backgroundColor: colors.primary,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  createButtonText: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  filtersContainer: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  filterChip: {
    backgroundColor: colors.chipBg,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    marginRight: 10,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
  },
  filterText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  filterTextActive: {
    color: colors.onPrimary,
    fontWeight: "600",
  },
  feed: {
    paddingHorizontal: 16,
    gap: 20,
  },
  postCard: {
    backgroundColor: colors.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingBottom: 12,
  },
  postUserInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  postUserNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  postUserName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  verifiedBadge: {
    backgroundColor: colors.link,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  verifiedText: {
    color: colors.onPrimary,
    fontSize: 10,
    fontWeight: "bold",
  },
  postMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  postTime: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  postMetaDot: {
    fontSize: 12,
    color: colors.textMuted,
  },
  publicBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  publicText: {
    fontSize: 10,
    color: colors.primaryDark,
  },
  deleteButton: {
    padding: 8,
  },
  postContent: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  postContentText: {
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
  },
  readMore: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600",
    marginTop: 8,
  },
  postMedia: {
    marginBottom: 12,
  },
  postImage: {
    width: "100%",
    height: 280,
    backgroundColor: colors.chipBg,
  },
  videoPlaceholder: {
    width: "100%",
    height: 280,
    backgroundColor: colors.videoBg,
    alignItems: "center",
    justifyContent: "center",
  },
  videoText: {
    color: colors.onPrimary,
    fontSize: 18,
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  tag: {
    backgroundColor: colors.chipBg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  tagText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  engagementStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  likesInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  likeIconContainer: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  likeIcon: {
    color: colors.onPrimary,
    fontSize: 10,
  },
  likesCount: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  commentsCount: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: "500",
  },
  postActions: {
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: colors.background,
    flex: 1,
    justifyContent: "center",
  },
  actionButtonActive: {
    backgroundColor: colors.dangerSoft,
  },
  actionButtonText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  actionButtonTextActive: {
    color: colors.danger,
  },
  shareWrapper: {
    flex: 1,
    position: "relative",
  },
  tooltip: {
    position: "absolute",
    bottom: 50,
    left: "50%",
    transform: [{ translateX: -50 }],
    backgroundColor: colors.videoBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    zIndex: 10,
  },
  tooltipText: {
    color: colors.onPrimary,
    fontSize: 12,
  },
  commentsSection: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  commentItem: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  commentItemNested: {
    marginLeft: 44,
    marginTop: 12,
  },
  commentContent: {
    flex: 1,
  },
  commentBubble: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  commentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  commentUserName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
  },
  commentTime: {
    fontSize: 10,
    color: colors.textMuted,
  },
  commentText: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    marginBottom: 8,
  },
  commentFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  commentLikeText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  commentReplyText: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: "600",
  },
  replyContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
  },
  replyInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  replyInput: {
    flex: 1,
    paddingVertical: 8,
    fontSize: 13,
    color: colors.text,
  },
  commentInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 16,
  },
  commentInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  commentInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.text,
    maxHeight: 100,
  },
  commentSendButton: {
    padding: 8,
  },
  signInPrompt: {
    alignItems: "center",
    paddingVertical: 16,
  },
  signInText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  avatar: {
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarText: {
    color: colors.onPrimary,
    fontWeight: "700",
  },
  onlineDot: {
    position: "absolute",
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.card,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: "center",
    paddingHorizontal: 40,
  },
  footer: {
    paddingVertical: 20,
    alignItems: "center",
  },
  footerText: {
    fontSize: 12,
    color: colors.textMuted,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.card,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  modalUserInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  modalUserName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
  },
  modalInput: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    color: colors.text,
    minHeight: 120,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 8,
  },
  charCounter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    marginBottom: 16,
  },
  charDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  charDotWarning: {
    backgroundColor: colors.danger,
  },
  charText: {
    fontSize: 12,
    color: colors.textMuted,
  },
  charTextWarning: {
    color: colors.danger,
  },
  modalMediaPreview: {
    position: "relative",
    marginBottom: 20,
  },
  modalPreviewImage: {
    width: "100%",
    height: 200,
    borderRadius: 16,
  },
  videoPreview: {
    width: "100%",
    height: 200,
    backgroundColor: colors.videoBg,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  videoPreviewText: {
    color: colors.onPrimary,
    fontSize: 16,
  },
  removeMediaButton: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: colors.card,
    borderRadius: 20,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  mediaButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.background,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mediaButtonText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "500",
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
  },
  submitButtonDisabled: {
    backgroundColor: colors.textMuted,
  },
  submitButtonText: {
    color: colors.onPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
});
