import { Platform, StyleSheet } from "react-native";

export const createCommunityStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
      gap: 16,
    },
    loadingRing: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.primarySoft,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 6,
    },
    loadingText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.textSecondary,
      letterSpacing: 0.3,
    },
    heroHeader: {
      paddingTop: Platform.OS === "ios" ? 56 : 20,
      paddingHorizontal: 20,
      paddingBottom: 20,
      backgroundColor: colors.primarySoft,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      marginBottom: 16,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 6,
    },
    heroHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      marginBottom: 16,
    },
    heroIconCircle: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    headerTextWrap: {
      flex: 1,
    },
    heroTitle: {
      fontSize: 26,
      fontWeight: "900",
      color: colors.text,
      letterSpacing: -0.8,
    },
    heroSubtitle: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.textSecondary,
      marginTop: 2,
    },
    authBanner: {
      marginBottom: 12,
      padding: 14,
      borderRadius: 14,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    authBannerText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 10,
    },
    authBannerActions: {
      flexDirection: "row",
      gap: 10,
    },
    authPrimaryButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: colors.primary,
      alignItems: "center",
    },
    authPrimaryButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.onPrimary,
    },
    authSecondaryButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
    },
    authSecondaryButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.primary,
    },
    loggedInBanner: {
      marginBottom: 10,
      paddingVertical: 6,
    },
    loggedInText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.primaryDark,
    },
    feedErrorBanner: {
      marginHorizontal: 20,
      marginBottom: 12,
      padding: 14,
      borderRadius: 14,
      backgroundColor: colors.dangerSoft,
      borderWidth: 1,
      borderColor: colors.danger,
    },
    feedErrorText: {
      fontSize: 13,
      color: colors.danger,
      lineHeight: 18,
      marginBottom: 10,
    },
    feedRetryButton: {
      alignSelf: "flex-start",
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: colors.primary,
      marginBottom: 8,
    },
    feedRetryButtonText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.onPrimary,
    },
    feedErrorHint: {
      fontSize: 10,
      color: colors.textMuted,
    },
    emptySignInButton: {
      marginTop: 16,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: colors.primary,
    },
    emptySignInButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.onPrimary,
    },
    statsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 14,
    },
    statPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 7,
      backgroundColor: colors.card,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statPillText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.textSecondary,
    },
    statPillWarn: {
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger + "33",
    },
    statPillTextWarn: {
      color: colors.danger,
      fontSize: 12,
      fontWeight: "700",
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 20,
      marginBottom: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 2,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
      fontWeight: "500",
      paddingVertical: 2,
    },
    createCard: {
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 20,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
      overflow: "hidden",
    },
    createCardInner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      padding: 16,
    },
    createCardIcon: {
      width: 52,
      height: 52,
      borderRadius: 18,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    createCardTextWrap: {
      flex: 1,
    },
    createCardTitle: {
      fontSize: 16,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 2,
    },
    createCardSubtitle: {
      fontSize: 13,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    filtersContainer: {
      paddingHorizontal: 16,
      marginBottom: 18,
      gap: 8,
    },
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.card,
      borderRadius: 24,
      marginRight: 10,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 1,
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    filterText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textSecondary,
    },
    filterTextActive: {
      color: colors.onPrimary,
    },
    feed: {
      paddingHorizontal: 20,
      gap: 20,
    },
    postCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 4,
      marginBottom: 4,
    },
    trendingBadge: {
      position: "absolute",
      top: 14,
      left: 14,
      zIndex: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 5,
      backgroundColor: colors.warning,
      borderRadius: 20,
      shadowColor: colors.warning,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    trendingText: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.onPrimary,
      letterSpacing: 0.3,
    },
    postHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 18,
      paddingBottom: 12,
    },
    postUserInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      flex: 1,
    },
    postUserMeta: {
      flex: 1,
    },
    postUserNameRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    postUserName: {
      fontSize: 16,
      fontWeight: "800",
      color: colors.text,
      letterSpacing: -0.2,
    },
    verifiedBadge: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    postMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      marginTop: 3,
    },
    postTime: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    postMetaDot: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: "700",
    },
    publicBadge: {
      backgroundColor: colors.primarySoft,
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 6,
    },
    publicText: {
      fontSize: 10,
      fontWeight: "800",
      color: colors.primaryDark,
      letterSpacing: 0.3,
    },
    deleteButton: {
      padding: 8,
      borderRadius: 10,
      backgroundColor: colors.dangerSoft,
    },
    postContent: {
      paddingHorizontal: 18,
      paddingBottom: 14,
    },
    postContentText: {
      fontSize: 15,
      color: colors.text,
      lineHeight: 22,
      fontWeight: "400",
    },
    readMore: {
      fontSize: 14,
      color: colors.primary,
      fontWeight: "800",
      marginTop: 8,
    },
    postMedia: {
      marginBottom: 12,
    },
    postImage: {
      width: "100%",
      height: 280,
      backgroundColor: colors.chipBg,
    },
    videoPlaceholder: {
      width: "100%",
      height: 280,
      backgroundColor: colors.videoBg,
      alignItems: "center",
      justifyContent: "center",
    },
    videoText: {
      color: colors.onPrimary,
      fontSize: 18,
      fontWeight: "700",
    },
    tagsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 18,
      paddingBottom: 14,
      gap: 8,
    },
    tag: {
      backgroundColor: colors.primarySoft,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 10,
    },
    tagText: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.primaryDark,
      letterSpacing: 0.3,
    },
    engagementStats: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    likesInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    likeIconContainer: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.danger,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.danger,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    likesCount: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textSecondary,
    },
    commentsCount: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.primary,
    },
    postActions: {
      flexDirection: "row",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 6,
    },
    actionButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 14,
      backgroundColor: colors.background,
      flex: 1,
    },
    actionButtonActive: {
      backgroundColor: colors.dangerSoft,
    },
    actionButtonActiveComment: {
      backgroundColor: colors.primarySoft,
    },
    actionButtonText: {
      fontSize: 13,
      fontWeight: "800",
      color: colors.textSecondary,
    },
    actionButtonTextActive: {
      color: colors.danger,
    },
    actionButtonTextActiveComment: {
      color: colors.primary,
    },
    shareWrapper: {
      flex: 1,
      position: "relative",
    },
    tooltip: {
      position: "absolute",
      bottom: 46,
      left: "50%",
      marginLeft: -40,
      backgroundColor: colors.videoBg || colors.text,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      zIndex: 10,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    tooltipText: {
      color: colors.onPrimary || "#ffffff",
      fontSize: 11,
      fontWeight: "800",
    },
    commentsSection: {
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
    commentItem: {
      flexDirection: "row",
      gap: 12,
      marginBottom: 14,
    },
    commentItemNested: {
      marginLeft: 44,
      marginTop: 10,
    },
    commentContent: {
      flex: 1,
    },
    commentBubble: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 4,
      elevation: 1,
    },
    commentHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    commentUserName: {
      fontSize: 13,
      fontWeight: "800",
      color: colors.text,
    },
    commentTime: {
      fontSize: 10,
      fontWeight: "600",
      color: colors.textMuted,
    },
    commentText: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
      marginBottom: 8,
    },
    commentFooter: {
      flexDirection: "row",
      alignItems: "center",
      gap: 18,
    },
    commentLikeText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.textSecondary,
    },
    commentReplyText: {
      fontSize: 12,
      fontWeight: "800",
      color: colors.primary,
    },
    replyContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginTop: 10,
    },
    replyInputWrapper: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.background,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    replyInput: {
      flex: 1,
      paddingVertical: 8,
      fontSize: 13,
      color: colors.text,
      fontWeight: "500",
    },
    commentInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 16,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    commentInputWrapper: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingVertical: 4,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 2,
    },
    commentInput: {
      flex: 1,
      paddingVertical: 12,
      fontSize: 14,
      color: colors.text,
      maxHeight: 100,
      fontWeight: "500",
    },
    commentSendButton: {
      padding: 8,
      marginLeft: 4,
    },
    signInPrompt: {
      alignItems: "center",
      paddingVertical: 16,
      backgroundColor: colors.primarySoft,
      borderRadius: 14,
      marginTop: 8,
    },
    signInText: {
      color: colors.primaryDark,
      fontSize: 14,
      fontWeight: "800",
    },
    avatar: {
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    avatarImage: {
      width: "100%",
      height: "100%",
    },
    avatarText: {
      color: "#ffffff",
      fontWeight: "900",
      letterSpacing: 0.5,
    },
    onlineDot: {
      position: "absolute",
      backgroundColor: "#22c55e",
      borderWidth: 2,
      borderColor: colors.card,
      shadowColor: "#22c55e",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 2,
    },
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
      paddingHorizontal: 24,
    },
    emptyIconCircle: {
      width: 80,
      height: 80,
      borderRadius: 28,
      backgroundColor: colors.primarySoft,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    emptyTitle: {
      fontSize: 20,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 8,
      letterSpacing: -0.3,
    },
    emptyText: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.textSecondary,
      textAlign: "center",
      lineHeight: 20,
    },
    footer: {
      paddingVertical: 24,
      alignItems: "center",
    },
    footerText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textMuted,
      letterSpacing: 0.3,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 20,
      paddingTop: Platform.OS === "ios" ? 56 : 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "900",
      color: colors.text,
      letterSpacing: -0.5,
    },
    modalContent: {
      flex: 1,
      padding: 20,
    },
    modalUserInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      marginBottom: 20,
    },
    modalUserName: {
      fontSize: 16,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 4,
    },
    modalInput: {
      backgroundColor: colors.background,
      borderRadius: 20,
      padding: 18,
      fontSize: 16,
      color: colors.text,
      minHeight: 140,
      textAlignVertical: "top",
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
      lineHeight: 22,
      fontWeight: "500",
    },
    charCounter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 6,
      marginBottom: 16,
    },
    charDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.primary,
    },
    charDotWarning: {
      backgroundColor: colors.danger,
    },
    charText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.textMuted,
    },
    charTextWarning: {
      color: colors.danger,
    },
    modalMediaPreview: {
      position: "relative",
      marginBottom: 20,
      borderRadius: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalPreviewImage: {
      width: "100%",
      height: 220,
      borderRadius: 20,
    },
    videoPreview: {
      width: "100%",
      height: 220,
      backgroundColor: colors.videoBg,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    videoPreviewText: {
      color: colors.onPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    removeMediaButton: {
      position: "absolute",
      top: 10,
      right: 10,
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 4,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 3,
    },
    modalTagSection: {
      marginBottom: 16,
    },
    modalTagLabel: {
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 8,
    },
    modalTagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    modalTagChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
    },
    modalTagChipText: {
      fontSize: 12,
      fontWeight: "600",
    },
    modalActions: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 24,
    },
    mediaButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      flex: 1,
      paddingVertical: 12,
      backgroundColor: colors.background,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 1,
    },
    mediaButtonText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
    },
    submitButton: {
      paddingVertical: 18,
      borderRadius: 20,
      alignItems: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 6,
    },
    submitButtonDisabled: {
      opacity: 0.4,
      shadowOpacity: 0,
      elevation: 0,
    },
    submitButtonText: {
      color: colors.onPrimary,
      fontSize: 16,
      fontWeight: "900",
      letterSpacing: 0.5,
    },
  });