export const createDiseaseStyles = (colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  // Hero Section
  heroSection: {
    backgroundColor: colors.heroGradientStart,
    margin: 16,
    marginTop: 20,
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  badgeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: "flex-start",
    gap: 6,
  },
  badgeText: {
    fontSize: 12,
    color: colors.primaryDark,
    fontWeight: "600",
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: colors.text,
    lineHeight: 40,
    marginBottom: 12,
  },
  heroTitleGreen: {
    color: colors.primary,
  },
  heroSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  // Two Column Layout
  twoColumnSection: {
    paddingHorizontal: 16,
    gap: 20,
    marginBottom: 24,
  },
  // Upload Card
  uploadCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  uploadTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 4,
  },
  uploadSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  uploadArea: {
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.border,
    borderStyle: "dashed",
    borderRadius: 16,
    padding: 32,
    alignItems: "center",
    marginBottom: 16,
  },
  uploadAreaText: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 12,
    marginBottom: 4,
  },
  uploadAreaHint: {
    fontSize: 11,
    color: colors.textMuted,
  },
  imagePreviewContainer: {
    alignItems: "center",
  },
  previewImage: {
    width: 150,
    height: 150,
    borderRadius: 12,
    marginBottom: 12,
  },
  clearImageButton: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: colors.danger,
    borderRadius: 12,
    padding: 4,
  },
  previewText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: "500",
    marginTop: 8,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  cameraButton: {
    backgroundColor: colors.link,
  },
  galleryButton: {
    backgroundColor: colors.warning,
  },
  actionButtonText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  analyzeButton: {
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
    marginBottom: 12,
  },
  analyzeButtonDisabled: {
    backgroundColor: colors.textMuted,
  },
  analyzeButtonText: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  resetButton: {
    alignItems: "center",
    paddingVertical: 10,
  },
  resetButtonText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  // How It Works
  howItWorksCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  howItWorksTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 8,
  },
  howItWorksSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 20,
    lineHeight: 20,
  },
  stepsContainer: {
    gap: 16,
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  stepNumberText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
  },
  // Supported Crops
  supportedCropsSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    marginHorizontal: 20,
    marginBottom: 16,
  },
  cropsScroll: {
    paddingHorizontal: 16,
  },
  cropCard: {
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    marginRight: 12,
    minWidth: 100,
  },
  cropCardDisabled: {
    opacity: 0.6,
  },
  cropIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  cropName: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
  },
  cropNameDisabled: {
    color: colors.textMuted,
  },
  comingSoon: {
    fontSize: 10,
    color: colors.textSecondary,
    marginTop: 4,
  },
  cropCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  availableBadge: {
    fontSize: 10,
    color: colors.primaryDark,
    fontWeight: "700",
    marginTop: 4,
  },
  cropNote: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 8,
    marginHorizontal: 20,
  },
  // Result Card
  resultCard: {
    backgroundColor: colors.dangerSoft,
    marginHorizontal: 20,
    marginBottom: 24,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  resultHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  resultTitleContainer: {
    flex: 1,
    marginLeft: 12,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.danger,
  },
  confidenceBadge: {
    backgroundColor: colors.danger,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  confidenceText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: "600",
  },
  diseaseName: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.danger,
    marginBottom: 8,
  },
  severityText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.warning,
    marginBottom: 16,
  },
  treatmentCard: {
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
  },
  treatmentHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  treatmentTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primaryDark,
    marginLeft: 8,
  },
  treatmentItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 8,
  },
  treatmentBullet: {
    fontSize: 14,
    color: colors.primary,
  },
  treatmentText: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
  },
  modelInfo: {
    fontSize: 11,
    color: colors.danger,
    textAlign: "center",
  },
  // Result Preview
  resultPreviewCard: {
    backgroundColor: colors.card,
    marginHorizontal: 20,
    marginBottom: 24,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  resultPreviewTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.text,
    textAlign: "center",
    marginBottom: 8,
  },
  resultPreviewSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: 20,
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  statBox: {
    flex: 1,
    backgroundColor: colors.heroGradientStart,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
  },
  statLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  statValueBlue: {
    color: colors.link,
  },
  statValueYellow: {
    color: colors.warning,
  },
  previewTreatmentBox: {
    backgroundColor: colors.heroGradientStart,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewTreatmentTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primaryDark,
    marginBottom: 12,
  },
  previewTreatmentItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 8,
  },
  previewTreatmentBullet: {
    fontSize: 12,
    color: colors.primary,
  },
  previewTreatmentText: {
    flex: 1,
    fontSize: 12,
    color: colors.text,
  },
  // Trust Features
  trustContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 16,
    marginBottom: 32,
  },
  trustCard: {
    flex: 1,
    minWidth: "30%",
    alignItems: "center",
    textAlign: "center",
  },
  trustIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  trustTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 4,
    textAlign: "center",
  },
  trustDescription: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: "center",
  },
  // CTA Section
  ctaSection: {
    backgroundColor: colors.primary,
    marginHorizontal: 20,
    marginBottom: 24,
    padding: 32,
    borderRadius: 24,
    alignItems: "center",
  },
  ctaTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: colors.onPrimary,
    textAlign: "center",
    marginBottom: 8,
  },
  ctaSubtitle: {
    fontSize: 14,
    color: colors.primarySoft,
    textAlign: "center",
    marginBottom: 20,
  },
  ctaButton: {
    backgroundColor: colors.card,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 30,
    gap: 8,
  },
  ctaButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primaryDark,
  },
  futureNote: {
    fontSize: 11,
    color: colors.textSecondary,
    marginHorizontal: 20,
    marginBottom: 30,
    paddingTop: 12,
    textAlign: "center",
    fontStyle: "italic",
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.card,
    borderRadius: 24,
    width: "90%",
    maxHeight: "80%",
    overflow: "hidden",
  },
  sourceModalContent: {
    width: "88%",
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: 20,
  },
  sourceModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 8,
  },
  sourceModalSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
    marginBottom: 16,
  },
  sourceButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    marginBottom: 10,
  },
  sourceButtonText: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  sourceCancelButton: {
    alignItems: "center",
    paddingVertical: 10,
    marginTop: 2,
  },
  sourceCancelButtonText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
  },
  modalBody: {
    padding: 20,
  },
  closeModalButton: {
    backgroundColor: colors.primary,
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 10,
  },
  closeModalButtonText: {
    color: colors.onPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
});
